### ISSUE TITLE
Question: Why use cordova-plugin-browsertab instead of cordova-plugin-inappbrowser

### ISSUE THREAD

**Issue by ddurham2** [jy95/keycloak-capacitor#17]
@jy95 - I wanted to ask why you used cordova-plugin-browsertab instead of cordova-plugin-inappbrowser.

browsertab doesn't offer any customizations of the browser interface, whereas inappbrowser does, and there is example of passing the caller-defined options into inappbrowser.open(...) in keycloak-js already.

Was it just a decision based on wanting to get something up and going quickly or was there a technical reason?

Android looks fine, but I've noticed on iOS that there are some undesirable elements of the browser interface that break the illusion that you're in a native app.. most egregious being the Share button and the Safari button in the bottom right that will open the url in external Safari.  I can live with this, but it was some polish I was trying to clean up.

Thanks in advance for the info and history on it.

**Comment by jy95** [comment]
Hello, one of the reasons is kind simple : because [keycloak-ionic](https://github.com/JohannesBauer97/keycloak-ionic) did that.
(It was referred in Ionic documentation v3 : https://ionicframework.com/docs/v3/native/browser-tab/ )

If I remember correctly, IOS validation process refuses apps that uses a in-app browser (for security & safety reasons Apple used) whereas Android don't care. As well that storing cookies and running js code ...
Extra information can be found on the web like : 
- https://developer.okta.com/blog/2022/01/13/mobile-sso 
- https://krausefx.com/blog/announcing-inappbrowsercom-see-what-javascript-commands-get-executed-in-an-in-app-browser
- https://developer.apple.com/design/human-interface-guidelines/components/content/web-views/
- ... (many more)

**Comment by ddurham2** [comment]
Interesting.. I'm more familiar with the Android side, but that looks like a bit of a mess.

   At the moment, I'm only testing in the simulator, and I believe I've noticed that my app (using keycloak-capacitor) will remain signed in when I kill and restart the app, but I believe it will be signed out after a device restart.  Is that expected, and possibly caused by the behaviors explained above?  Or should it be possible for SSO to be persistent across device restarts, using keycloak-capacitor?

Thanks again

**Comment by jy95** [comment]
At the end, all depends of your configuration & needs ;)
keycloak-capacitor is agnostic about choices done by others such as : 
- SSO expiration time
- access token ttl
- refresh token
- ....

If you want to be log out, it should be done explicitly https://www.keycloak.org/docs/latest/securing_apps/index.html#logout
Otherwise, as long your cookie / session is still valid, you remain connected.

**Comment by ddurham2** [comment]
(Testing on an actual device now and getting the same behavior)

Yes, I understand that to be the case.  I have days long SSO and 5 minute access token.  And even now on a real device, everytime I kill and run the app again it requires login.  So I figure it must have something to do with the cookie or local storage on the browsertab's browser instance getting destroyed between runs.  Any ideas?

**Comment by ddurham2** [comment]
(I'm now testing on all physical devices.)

I understand about the server configuration.  Presently, in the Realm -> Token configuration, I've got all the **Session Idle Time**s set to _days_ long, all the **Session Max**es set to _days_, and **Access Token** to 15 minutes.   And I'm not overriding these values in the specific client configuration.

The behavior now is:
- iOS: SSO doesn't survive killing the app and restarting it.
- Android: SSO survives killing the app, but doesn't survive restarting the device.

I say SSO doesn't survive... By this I mean that:
- onLoad is _check-sso_ in the keycloak initialization
- the app calls keycloak.isLoggedIn toward the beginning of the process, it returns false.  (even if I delay calling it by several seconds)
- having the user then log in, calling keycloak.login() opens the browser tab to keycloak's login page, and after returning to the app, isLoggedIn() returns true

The reason I ask here is because I wonder if it has to do with the local or cookie storage of the browser tab that it uses to store SSO session token.  Does that storage get destroyed in the above circumstances?  Is there something my app needs to do to preserve it?

Thanks again

**Comment by ddurham2** [comment]
Maybe nevermind.. Upon further digging, what I'm looking for seems to be the intentional behavior for local user accounts with remember me unchecked (makes sense), and when remember me is checked, it works as it should (surviving browser restart).

However, I was originally testing with an OIDC social media account, and _that_ doesn't seem to have a remember me option (where it makes the session cookie survive a browser restart).  Additionally, iOS and Android seem to differ on exactly when session-expiration cookies actually expire.

I'd be obliged if anyone had an pointers on how to enable "remember me" type behavior for OIDC logins.  web searches haven't been much help yet.
